### PR TITLE
[Improvement] Change helper text for date of birth

### PR DESCRIPTION
**Pull request by leogjhuang**
## Notion ticket link

[Date of birth helper text](https://www.notion.so/uwblueprintexecs/Date-of-birth-helper-text-7d8a5328ea34443592ba7e0e2985dbfe)

## Implementation description
* Edit DOB helper text to avoid confusion for those using the mobile date picker
* Mention that the year can be changed by clicking the year for Android users

## Checklist
- [x] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

### CODE REVIEW

**Comment by kj3moraes** [comment]
The following pictures are from respective phones. @leogjhuang don't you think it might be too small to read ? 

Perhaps having an [admonition](https://chakra-ui.com/docs/components/alert/usage) instead would be better ?

#### Pixel 7 
CleanShot 2024-02-13 at 18 48 22@2x

#### iPhone 12 Pro 
CleanShot 2024-02-13 at 18 48 32@2x

**Comment by leogjhuang** [comment]
> The following pictures are from respective phones. @leogjhuang don't you think it might be too small to read ?
> 
> Perhaps having an [admonition](https://chakra-ui.com/docs/components/alert/usage) instead would be better ?
> 
> #### Pixel 7
> CleanShot 2024-02-13 at 18 48 22@2x
> 
> #### iPhone 12 Pro
> CleanShot 2024-02-13 at 18 48 32@2x



> The following pictures are from respective phones. @leogjhuang don't you think it might be too small to read ?
> 
> Perhaps having an [admonition](https://chakra-ui.com/docs/components/alert/usage) instead would be better ?
> 
> #### Pixel 7
> CleanShot 2024-02-13 at 18 48 22@2x
> 
> #### iPhone 12 Pro
> CleanShot 2024-02-13 at 18 48 32@2x

@kj3moraes I agree that the default Chakra UI `FormHelperText` may be on the smaller end, but since it is used throughout the application, addressing this issue might be outside the scope of the ticket.

**Comment by kj3moraes** [comment]
Fair enough. Everything else looks good.

**Review by kj3moraes — APPROVED** [review]

**Review by ChinemeremChigbo — APPROVED** [review]
LGTM

**Pull request merged**
